---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
