---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume-jenkins
  namespace: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
